apiVersion: apps/v1
kind: Deployment
metadata:
  name: prov-template-catalog
spec:
  selector:
    matchLabels:
      app: prov-template-catalog
  replicas: 1
  template:
    metadata:
      labels:
        app: prov-template-catalog
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: prov-template
          image: registry.gitlab.com/knmi-oss/swirrl/swirrl-api/prov-template-catalog:latest
          # imagePullPolicy: Never
          command: ["/tmp/ProvTemplateCatalog/docker-cmd.sh"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prov-template-conf
              mountPath: /etc/httpd/conf.d/prov-template.conf
              subPath: prov-template.conf
          envFrom:
            - configMapRef:
                name: prov-template-oauth
          env:
            - name: PROV_TMPL_MONGODB_HOSTPORT
              value: prov-template-catalog-mongodb
            - name: PROV_TMPL_SERVERNAME
              valueFrom:
                configMapKeyRef:
                  name: server-url-jwt-conf
                  key: prov-tmpl.servername
            - name: PROV_TMPL_BASEURL_HOST
              valueFrom:
                configMapKeyRef:
                  name: server-url-jwt-conf
                  key: prov-tmpl.baseurl
            - name: PROV_TMPL_JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: server-url-jwt-conf
                  key: prov-tmpl.jwt
      volumes:
        - name: prov-template-conf
          configMap:
            name: prov-template-conf
  strategy:
    type: Recreate
---
kind: Service
apiVersion: v1
metadata:
  name: prov-template-catalog
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    app: prov-template-catalog
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: prov-template-catalog
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /template-catalog(.+)
            backend:
              serviceName: prov-template-catalog
              servicePort: 80
